// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using test_peformance;

#nullable disable

namespace test_peformance.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240224151052_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("test_peformance.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Department", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "phunn"
                        });
                });

            modelBuilder.Entity("test_peformance.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("text");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Name = "Employee_1",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Name = "Employee_2",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 1,
                            Name = "Employee_3",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Name = "Employee_4",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 1,
                            Name = "Employee_5",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 1,
                            Name = "Employee_6",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 1,
                            Name = "Employee_7",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 1,
                            Name = "Employee_8",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 1,
                            Name = "Employee_9",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 1,
                            Name = "Employee_10",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 1,
                            Name = "Employee_11",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 1,
                            Name = "Employee_12",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 1,
                            Name = "Employee_13",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 1,
                            Name = "Employee_14",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 1,
                            Name = "Employee_15",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 1,
                            Name = "Employee_16",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 1,
                            Name = "Employee_17",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 1,
                            Name = "Employee_18",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 1,
                            Name = "Employee_19",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 1,
                            Name = "Employee_20",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 1,
                            Name = "Employee_21",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 1,
                            Name = "Employee_22",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 1,
                            Name = "Employee_23",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 1,
                            Name = "Employee_24",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 1,
                            Name = "Employee_25",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 1,
                            Name = "Employee_26",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 1,
                            Name = "Employee_27",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 28,
                            DepartmentId = 1,
                            Name = "Employee_28",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 29,
                            DepartmentId = 1,
                            Name = "Employee_29",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 30,
                            DepartmentId = 1,
                            Name = "Employee_30",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 31,
                            DepartmentId = 1,
                            Name = "Employee_31",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 32,
                            DepartmentId = 1,
                            Name = "Employee_32",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 33,
                            DepartmentId = 1,
                            Name = "Employee_33",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 34,
                            DepartmentId = 1,
                            Name = "Employee_34",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 35,
                            DepartmentId = 1,
                            Name = "Employee_35",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 36,
                            DepartmentId = 1,
                            Name = "Employee_36",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 37,
                            DepartmentId = 1,
                            Name = "Employee_37",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 38,
                            DepartmentId = 1,
                            Name = "Employee_38",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 39,
                            DepartmentId = 1,
                            Name = "Employee_39",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 40,
                            DepartmentId = 1,
                            Name = "Employee_40",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 41,
                            DepartmentId = 1,
                            Name = "Employee_41",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 42,
                            DepartmentId = 1,
                            Name = "Employee_42",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 43,
                            DepartmentId = 1,
                            Name = "Employee_43",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 44,
                            DepartmentId = 1,
                            Name = "Employee_44",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 45,
                            DepartmentId = 1,
                            Name = "Employee_45",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 46,
                            DepartmentId = 1,
                            Name = "Employee_46",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 47,
                            DepartmentId = 1,
                            Name = "Employee_47",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 48,
                            DepartmentId = 1,
                            Name = "Employee_48",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 49,
                            DepartmentId = 1,
                            Name = "Employee_49",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 50,
                            DepartmentId = 1,
                            Name = "Employee_50",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 51,
                            DepartmentId = 1,
                            Name = "Employee_51",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 52,
                            DepartmentId = 1,
                            Name = "Employee_52",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 53,
                            DepartmentId = 1,
                            Name = "Employee_53",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 54,
                            DepartmentId = 1,
                            Name = "Employee_54",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 55,
                            DepartmentId = 1,
                            Name = "Employee_55",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 56,
                            DepartmentId = 1,
                            Name = "Employee_56",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 57,
                            DepartmentId = 1,
                            Name = "Employee_57",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 58,
                            DepartmentId = 1,
                            Name = "Employee_58",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 59,
                            DepartmentId = 1,
                            Name = "Employee_59",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 60,
                            DepartmentId = 1,
                            Name = "Employee_60",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 61,
                            DepartmentId = 1,
                            Name = "Employee_61",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 62,
                            DepartmentId = 1,
                            Name = "Employee_62",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 63,
                            DepartmentId = 1,
                            Name = "Employee_63",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 64,
                            DepartmentId = 1,
                            Name = "Employee_64",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 65,
                            DepartmentId = 1,
                            Name = "Employee_65",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 66,
                            DepartmentId = 1,
                            Name = "Employee_66",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 67,
                            DepartmentId = 1,
                            Name = "Employee_67",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 68,
                            DepartmentId = 1,
                            Name = "Employee_68",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 69,
                            DepartmentId = 1,
                            Name = "Employee_69",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 70,
                            DepartmentId = 1,
                            Name = "Employee_70",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 71,
                            DepartmentId = 1,
                            Name = "Employee_71",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 72,
                            DepartmentId = 1,
                            Name = "Employee_72",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 73,
                            DepartmentId = 1,
                            Name = "Employee_73",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 74,
                            DepartmentId = 1,
                            Name = "Employee_74",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 75,
                            DepartmentId = 1,
                            Name = "Employee_75",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 76,
                            DepartmentId = 1,
                            Name = "Employee_76",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 77,
                            DepartmentId = 1,
                            Name = "Employee_77",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 78,
                            DepartmentId = 1,
                            Name = "Employee_78",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 79,
                            DepartmentId = 1,
                            Name = "Employee_79",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 80,
                            DepartmentId = 1,
                            Name = "Employee_80",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 81,
                            DepartmentId = 1,
                            Name = "Employee_81",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 82,
                            DepartmentId = 1,
                            Name = "Employee_82",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 83,
                            DepartmentId = 1,
                            Name = "Employee_83",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 84,
                            DepartmentId = 1,
                            Name = "Employee_84",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 85,
                            DepartmentId = 1,
                            Name = "Employee_85",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 86,
                            DepartmentId = 1,
                            Name = "Employee_86",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 87,
                            DepartmentId = 1,
                            Name = "Employee_87",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 88,
                            DepartmentId = 1,
                            Name = "Employee_88",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 89,
                            DepartmentId = 1,
                            Name = "Employee_89",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 90,
                            DepartmentId = 1,
                            Name = "Employee_90",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 91,
                            DepartmentId = 1,
                            Name = "Employee_91",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 92,
                            DepartmentId = 1,
                            Name = "Employee_92",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 93,
                            DepartmentId = 1,
                            Name = "Employee_93",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 94,
                            DepartmentId = 1,
                            Name = "Employee_94",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 95,
                            DepartmentId = 1,
                            Name = "Employee_95",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 96,
                            DepartmentId = 1,
                            Name = "Employee_96",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 97,
                            DepartmentId = 1,
                            Name = "Employee_97",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 98,
                            DepartmentId = 1,
                            Name = "Employee_98",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 99,
                            DepartmentId = 1,
                            Name = "Employee_99",
                            Salary = 10m
                        },
                        new
                        {
                            Id = 100,
                            DepartmentId = 1,
                            Name = "Employee_100",
                            Salary = 10m
                        });
                });

            modelBuilder.Entity("test_peformance.Entities.Employee", b =>
                {
                    b.HasOne("test_peformance.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("test_peformance.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
