name: CI - Build & Push

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - closed
    branches:
      - dev

jobs:
  build-and-push:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short git SHA (5 chars)
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/testperformance:${{ steps.vars.outputs.SHORT_SHA }}

      - name: Clone manifest repo
        env:
          MANIFEST_REPO_TOKEN: ${{ secrets.MANIFEST_REPO_TOKEN }}
        run: |
          git clone https://x-access-token:${MANIFEST_REPO_TOKEN}@github.com/NguyeNgocPhus/Builder.git

      - name: Update image tag in stack file
        env:
          SHORT_SHA: ${{ steps.vars.outputs.SHORT_SHA }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd Builder

          # Thay thế toàn bộ image line của order-service
          sed -i "s|image: nguyenphu/testperformance:.*|image: nguyenphu/testperformance:${SHORT_SHA}|" stasks/testperformance.yml

          # Verify kết quả
          grep "image:.*testperformance" stasks/testperformance.yml

      - name: Commit & Push to manifest repo
        env:
          SHORT_SHA: ${{ steps.vars.outputs.SHORT_SHA }}
        run: |
          cd Builder

          git config user.email "ci-bot@yourcompany.com"
          git config user.name "CI Bot"
          git add stasks/testperformance.yml
          git diff --cached --quiet || git commit -m "ci: update testperformance image tag to ${SHORT_SHA}"
          git push
